# This is a basic workflow to help you get started with Actions

name: main-CI
run-name: ${{github.actor}} is testing out GitHub Actions 🚀

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:

    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Create demo file
        run: |
          mkdir reports
          echo "hello from CI Pipeline" > reports/demo.txt
          echo "File created successfully"

      # upload whatever is here in the current folder
      - name: Upload Demo
        uses: actions/upload-artifact@v4
        with:
          name: build artifact demo
          path: reports
          
  tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run tests
        run: echo Running tests...

  explore-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: get general infos
        run: | 
          echo "the job was automatically triggered by a ${{github.event_name}}."
          echo "this job is now running on a ${{runner.os}} server hosted by GitHub."
          echo "the name of your branch is ${{github.ref}} and your repository is ${{github.repository}}."
      - name: checkout repository code    
        uses: actions/checkout@v5  
      - name: get other infos
        run: |  
          echo "the ${{github.repository}} repository has been cloned to the runner."
          echo "List fies in the repository"
          ls "${{github.workspace}}"
          echo "this job's status is ${{job.status}}"